apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-rh-1551989620:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-rh-1551989620:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: bdd-rh-1551989620
        chartPath: charts/bdd-rh-1551989620
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-rh-1551989620'
          image.tag: '{{.DIGEST_HEX}}'
